[project]
name = "a2a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=0.3.10",
    "aisuite[anthropic]>=0.1.6",
    "fastmcp>=2.13.0.2",
    "openai>=2.7.1",
    "python-dotenv>=1.2.1",
]
